import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { emailOTP } from "better-auth/plugins";

import { db, schema } from "@/db";
import { AUTH_EMAIL_FROM, getResend } from "@/lib/resend";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    schema,
  }),
  // IDs are uuids generated by Postgres (`defaultRandom()` in auth-schema),
  // so better-auth must NOT generate them itself -- it would emit text ids
  // that collide with the uuid columns and profiles' uuid FK.
  advanced: {
    database: {
      generateId: false,
    },
  },
  // Student-email OTP is the only sign-in path for the MVP. No passwords,
  // no phone (phoneVerified stays a column-only field for now).
  plugins: [
    emailOTP({
      async sendVerificationOTP({ email, otp }) {
        await getResend().emails.send({
          from: AUTH_EMAIL_FROM,
          to: email,
          subject: "Oper のログインコード",
          text: `ログインコード: ${otp}\n\nこのコードは10分間有効です。心当たりがない場合は無視してください。`,
        });
      },
    }),
  ],
});
